{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(pod_name) (jvm_memory_used_bytes{job=\"my-kotlin-app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "jvm_cpu_recent_utilization_ratio{job=\"my-kotlin-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rest 2XX, 3XX Response",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(pod_name, http_response_status_code) (increase(http_server_request_duration_seconds_count{job=\"my-kotlin-app\", http_response_status_code=~\"2..|3..\"}[2m]))/2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rest Request Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(pod_name) (increase(http_server_request_duration_seconds_count{job=\"my-kotlin-app\"}[2m]))/2",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}