---
# Source: my-kotlin-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-kotlin-app
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-kotlin-app
  template:
    metadata:
      labels:
        app: my-kotlin-app
    spec:
      containers:
        - name: my-kotlin-app
          image: ishuiyutian/my-kotlin-app:34
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector-collector.observability:4318
