name: CI

on:
  push:
    paths:
      - .github/workflows/ci.yml
      - app/**

# Test the workflow 9
jobs:
  build-app:
    uses: hongyuanlei/gh-workflow-java-maven/.github/workflows/java-maven-build.yml@master
    secrets: inherit
    with:
      working-directory: app